#!/usr/bin/env sh
# =============================================================================
# INSTALL HOOKS — Branch-independent hook installer
# =============================================================================
# Installs the upstream guard directly into .git/hooks/pre-push.
# Reads guard from main branch via `git show` (branch-independent).
# Run via: pnpm prepare | Manual: sh scripts/install-hooks.sh
# =============================================================================

set -e

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null)"
HOOKS_DIR="$REPO_ROOT/.git/hooks"
HOOK_FILE="$HOOKS_DIR/pre-push"

if [ -z "$REPO_ROOT" ]; then
  echo "install-hooks.sh: not inside a git repository, skipping."
  exit 0
fi

mkdir -p "$HOOKS_DIR"

# Read guard script from main branch (branch-independent)
GUARD_CONTENT="$(git show main:scripts/upstream-guard.sh 2>/dev/null)" || GUARD_CONTENT=""

cat > "$HOOK_FILE" << 'HOOKEOF'
#!/usr/bin/env sh
# =============================================================================
# COMBINED PRE-PUSH: Upstream Guard + Husky Hook
# Auto-generated by scripts/install-hooks.sh
# =============================================================================

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null)"

# --- UPSTREAM GUARD ---
HOOKEOF

if [ -n "$GUARD_CONTENT" ]; then
  echo "# --- BEGIN UPSTREAM GUARD ---" >> "$HOOK_FILE"
  echo "$GUARD_CONTENT" >> "$HOOK_FILE"
  echo "# --- END UPSTREAM GUARD ---" >> "$HOOK_FILE"
else
  echo "# Guard not found on main branch, skipping." >> "$HOOK_FILE"
fi

cat >> "$HOOK_FILE" << 'HOOKEOF'

# --- HUSKY HOOK ---
REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null)"
HUSKY_HOOK="$REPO_ROOT/.husky/pre-push"

if [ -f "$HUSKY_HOOK" ]; then
  sh "$HUSKY_HOOK" "$@"
  exit $?
fi

exit 0
HOOKEOF

chmod +x "$HOOK_FILE"
echo "✅ Pre-push hook installed to .git/hooks/pre-push (branch-independent)"
